/** Vendor the protocol modules the cabinet runs in the browser.
 *
 *    node tools/vendor-cabinet.mjs            copy protocol/*.js → cabinet/protocol/, write MANIFEST.json
 *    node tools/vendor-cabinet.mjs --check    exit 1 if any copy differs from source (demo/cabinet.test.mjs runs this)
 *
 *  The cabinet deploys as a static folder, so it cannot import ../protocol at
 *  runtime on Vercel; served by a node it could, but the two must be the same
 *  bytes either way. The manifest pins each copy by sha256 so drift is a test
 *  failure, not a "remember to re-copy" note in a README. */
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'protocol');
const dst = join(root, 'cabinet', 'protocol');
/** Everything the cabinet imports, directly or transitively. */
export const VENDORED = ['canonical.js', 'keys.js', 'keccak.js', 'staking.js', 'profile.js', 'abi.js', 'directory.js', 'derive.js', 'placement.js', 'pairing.js', 'snapshot.js', 'challenge.js', 'result.js', 'version.js', 'log.js', 'air.js'];
const sha = (b) => createHash('sha256').update(b).digest('hex');

/** The contract set, from contracts/deployed.testnet.json — the ONE place addresses live. Written as
 *  cabinet/contracts.js (imported by cabinet/config.js) and cabinet/contracts.json (fetched by titles that
 *  discover the mesh on their own: https://arcade.litvm.games/contracts.json, and /cabinet/contracts.json
 *  on every node). A generation flip is then one deploy + one release + one cabinet redeploy; nothing is
 *  copied by hand. Agent Fighter's client read a hand-copied generation-2 set for a day after the
 *  generation-3 deploy and showed SERVER OFFLINE (22 Sep 2026). */
export function contractSet() {
  const d = JSON.parse(readFileSync(join(root, 'contracts', 'deployed.testnet.json'), 'utf8'));
  const contracts = {};
  for (const [k, v] of Object.entries(d)) if (v && typeof v === 'object' && typeof v.address === 'string') contracts[k] = { address: v.address, ...(v.version != null ? { version: v.version } : {}), ...(v.block != null ? { block: v.block } : {}) };
  return { generation: d.generation ?? null, chainId: d.chainId ?? 4441, rpc: d.rpc ?? null, deployedAt: d.deployedAt ?? null, contracts };
}
const contractsJs = (set) => `/** GENERATED by tools/vendor-cabinet.mjs from contracts/deployed.testnet.json — do not edit. The cabinet's
 *  config.js reads addresses from here; demo/cabinet.test.mjs fails when this file lags the deploy. */
export const CONTRACTS = ${JSON.stringify(set, null, 2)};
`;
const contractsJson = (set) => JSON.stringify(set, null, 2) + String.fromCharCode(10);
export function checkContracts() {
  const set = contractSet();
  const out = [];
  const p = join(root, 'cabinet', 'contracts.js');
  if (!existsSync(p)) out.push('contracts.js: missing from cabinet/');
  else if (readFileSync(p, 'utf8') !== contractsJs(set)) out.push('contracts.js: lags contracts/deployed.testnet.json');
  const pj = join(root, 'cabinet', 'contracts.json');
  if (!existsSync(pj) || readFileSync(pj, 'utf8') !== contractsJson(set)) out.push('contracts.json: lags contracts/deployed.testnet.json');
  return out;
}

export function checkVendored() {
  const out = [];
  for (const f of VENDORED) {
    const a = readFileSync(join(src, f));
    const p = join(dst, f);
    if (!existsSync(p)) { out.push(`${f}: missing from cabinet/protocol`); continue; }
    if (sha(a) !== sha(readFileSync(p))) out.push(`${f}: differs from protocol/${f}`);
  }
  const mp = join(dst, 'MANIFEST.json');
  if (!existsSync(mp)) out.push('MANIFEST.json: missing');
  else {
    const m = JSON.parse(readFileSync(mp, 'utf8'));
    for (const f of VENDORED) if (m.files?.[f] !== sha(readFileSync(join(src, f)))) out.push(`${f}: manifest hash stale`);
  }
  out.push(...checkContracts());
  return out;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  if (process.argv.includes('--check')) {
    const bad = checkVendored();
    if (bad.length) { console.error(bad.join('\n')); console.error('run: node tools/vendor-cabinet.mjs'); process.exit(1); }
    console.log(`cabinet/protocol in sync (${VENDORED.length} files)`);
  } else {
    mkdirSync(dst, { recursive: true });
    const files = {};
    for (const f of VENDORED) { const b = readFileSync(join(src, f)); writeFileSync(join(dst, f), b); files[f] = sha(b); }
    writeFileSync(join(dst, 'MANIFEST.json'), JSON.stringify({ note: 'generated by tools/vendor-cabinet.mjs — do not edit copies by hand', files }, null, 2) + '\n');
    const set = contractSet();
    writeFileSync(join(root, 'cabinet', 'contracts.js'), contractsJs(set));
    writeFileSync(join(root, 'cabinet', 'contracts.json'), contractsJson(set));
    console.log(`vendored ${VENDORED.length} files → cabinet/protocol; contracts.js/.json ← deployed.testnet.json (${Object.keys(set.contracts).length} contracts)`);
  }
}
