/** Vendor the protocol modules the cabinet runs in the browser.
 *
 *    node tools/vendor-cabinet.mjs            copy protocol/*.js → cabinet/protocol/, write MANIFEST.json
 *    node tools/vendor-cabinet.mjs --check    exit 1 if any copy differs from source (demo/cabinet.test.mjs runs this)
 *
 *  The cabinet deploys as a static folder, so it cannot import ../protocol at
 *  runtime on Vercel; served by a node it could, but the two must be the same
 *  bytes either way. The manifest pins each copy by sha256 so drift is a test
 *  failure, not a "remember to re-copy" note in a README. */
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'protocol');
const dst = join(root, 'cabinet', 'protocol');
/** Everything the cabinet imports, directly or transitively. */
export const VENDORED = ['canonical.js', 'keys.js', 'keccak.js', 'staking.js', 'profile.js', 'abi.js', 'directory.js', 'derive.js', 'placement.js', 'pairing.js', 'snapshot.js'];
const sha = (b) => createHash('sha256').update(b).digest('hex');

export function checkVendored() {
  const out = [];
  for (const f of VENDORED) {
    const a = readFileSync(join(src, f));
    const p = join(dst, f);
    if (!existsSync(p)) { out.push(`${f}: missing from cabinet/protocol`); continue; }
    if (sha(a) !== sha(readFileSync(p))) out.push(`${f}: differs from protocol/${f}`);
  }
  const mp = join(dst, 'MANIFEST.json');
  if (!existsSync(mp)) out.push('MANIFEST.json: missing');
  else {
    const m = JSON.parse(readFileSync(mp, 'utf8'));
    for (const f of VENDORED) if (m.files?.[f] !== sha(readFileSync(join(src, f)))) out.push(`${f}: manifest hash stale`);
  }
  return out;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  if (process.argv.includes('--check')) {
    const bad = checkVendored();
    if (bad.length) { console.error(bad.join('\n')); console.error('run: node tools/vendor-cabinet.mjs'); process.exit(1); }
    console.log(`cabinet/protocol in sync (${VENDORED.length} files)`);
  } else {
    mkdirSync(dst, { recursive: true });
    const files = {};
    for (const f of VENDORED) { const b = readFileSync(join(src, f)); writeFileSync(join(dst, f), b); files[f] = sha(b); }
    writeFileSync(join(dst, 'MANIFEST.json'), JSON.stringify({ note: 'generated by tools/vendor-cabinet.mjs — do not edit copies by hand', files }, null, 2) + '\n');
    console.log(`vendored ${VENDORED.length} files → cabinet/protocol`);
  }
}
